/**
  Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

  Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
  Pentagonal	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
  Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
  It can be verified that T285 = P165 = H143 = 40755.

  Find the next triangle number that is also pentagonal and hexagonal.
*/

#include <iostream>

int main() {
  bool flag1 = false, flag2 = false;
  long long nextHexNum;
  for(long long h = 144; ; h++) {
    nextHexNum = h * (2 * h - 1);
    long long nextPentNum = 0;
    long long p;
    for(p = h; nextPentNum <= nextHexNum; p++) {
      nextPentNum = p * (3 * p - 1) / 2;
      if(nextPentNum == nextHexNum)
        flag1 = true;
    }

    long long nextTriNum = 0;
    if(flag1) {
      for(long long t = p; nextTriNum <= nextHexNum; t++) {
        nextTriNum = t * (t + 1) / 2;
        if(nextTriNum == nextHexNum)
          flag2 = true;
      }
    }
    if(flag1 and flag2)
      break;
  }
  std::cout << "The next triangle number that is both pentagonal and hexagonal is: " << nextHexNum << std::endl;
  return 0;
}